# Generated by Django 3.2.3 on 2022-10-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=3, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_names', models.CharField(blank=True, max_length=50, null=True)),
                ('propio_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('employee_active', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.city')),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillset', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transperfect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_names', models.CharField(blank=True, max_length=50, null=True)),
                ('transperfect_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('employee_active', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.city')),
                ('skillset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.skillset')),
            ],
        ),
        migrations.CreateModel(
            name='Transperfect_CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('shift_eof', models.CharField(blank=True, max_length=9, null=True)),
                ('eof_minutes', models.FloatField(blank=True, null=True)),
                ('shift_available', models.CharField(blank=True, max_length=9, null=True)),
                ('available_minutes', models.FloatField(blank=True, null=True)),
                ('shift_talk_time', models.CharField(blank=True, max_length=9, null=True)),
                ('talk_minutes', models.FloatField(blank=True, null=True)),
                ('shift_acw', models.CharField(blank=True, max_length=9, null=True)),
                ('acw_minutes', models.FloatField(blank=True, null=True)),
                ('shift_ring_through', models.CharField(blank=True, max_length=9, null=True)),
                ('ring_through_minutes', models.FloatField(blank=True, null=True)),
                ('shift_break', models.CharField(blank=True, max_length=9, null=True)),
                ('break_minutes', models.FloatField(blank=True, null=True)),
                ('shift_schedule_call', models.CharField(blank=True, max_length=9, null=True)),
                ('schedule_call_minutes', models.FloatField(blank=True, null=True)),
                ('shift_meeting', models.CharField(blank=True, max_length=9, null=True)),
                ('meeting_minutes', models.FloatField(blank=True, null=True)),
                ('shift_lunch', models.CharField(blank=True, max_length=9, null=True)),
                ('lunch_minutes', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.transperfect')),
            ],
        ),
        migrations.CreateModel(
            name='Propio_CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField(blank=True, null=True)),
                ('interaction_start_time', models.DateTimeField(blank=True, null=True)),
                ('interaction_length', models.CharField(blank=True, max_length=9, null=True)),
                ('interaction_length_minutes', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.propio')),
            ],
        ),
        migrations.AddField(
            model_name='propio',
            name='skillset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.skillset'),
        ),
        migrations.CreateModel(
            name='Production_Transperfect_CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('interaction_start_time', models.DateTimeField(blank=True, null=True)),
                ('interaction_end_time', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('minutes', models.FloatField(blank=True, null=True)),
                ('speed_answer', models.IntegerField(blank=True, null=True)),
                ('adjusted_minutes', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.transperfect')),
            ],
        ),
    ]
