# Generated by Django 3.2.3 on 2022-03-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Propio',
        ),
        migrations.CreateModel(
            name='Propio_CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField(blank=True, null=True)),
                ('interaction_start_time', models.TimeField(blank=True, null=True)),
                ('interaction_length', models.TimeField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.propio')),
            ],
        ),
    ]
