# Generated by Django 3.2.3 on 2022-03-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0002_auto_20220303_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propio_callhistory',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
