# Generated by Django 3.2.3 on 2022-03-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0003_auto_20220304_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='propio_callhistory',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.propio'),
        ),
    ]
