# Generated by Django 3.2.3 on 2022-03-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0004_propio_callhistory_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_length',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
