# Generated by Django 3.2.3 on 2022-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0005_auto_20220304_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
