# Generated by Django 3.2.3 on 2022-03-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0006_alter_propio_callhistory_interaction_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_length',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
