# Generated by Django 3.2.3 on 2022-03-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0007_alter_propio_callhistory_interaction_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='propio_callhistory',
            name='interaction_length_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
