# Generated by Django 3.2.3 on 2022-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0008_propio_callhistory_interaction_length_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propio_callhistory',
            name='interaction_length',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
