# Generated by Django 3.2.3 on 2022-03-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0010_auto_20220305_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillset', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='propio',
            old_name='interpreter_id',
            new_name='propio_id',
        ),
        migrations.AddField(
            model_name='propio',
            name='employee_active',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='propio',
            name='skillset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.skillset'),
        ),
    ]
