# Generated by Django 3.2.3 on 2022-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0011_auto_20220317_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propio',
            name='propio_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
