# Generated by Django 3.2.3 on 2022-04-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0012_alter_propio_propio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transperfect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_names', models.CharField(blank=True, max_length=50, null=True)),
                ('transperfect_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_active', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.city')),
                ('skillset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.skillset')),
            ],
        ),
        migrations.CreateModel(
            name='Transperfect_CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('shift_eof', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_available', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_talk_time', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_acw', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_ring_through', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_break', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_schedule_call', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_meeting', models.CharField(blank=True, max_length=9, null=True)),
                ('shift_lunch', models.CharField(blank=True, max_length=9, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reportes.transperfect')),
            ],
        ),
    ]
