# Generated by Django 3.2.3 on 2022-04-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0013_transperfect_transperfect_callhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
