# Generated by Django 3.2.3 on 2022-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0015_alter_transperfect_callhistory_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transperfect_callhistory',
            old_name='minutes',
            new_name='acw_minutes',
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='available_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='break_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='eof_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='lunch_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='meeting_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='ring_through_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='schedule_call_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transperfect_callhistory',
            name='talk_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
